### ISSUE TITLE
Presentation for sprint 1

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#12]
As Dr. Beaty, I want a presentation I might have y'all present on Thursday.
An upload on [Moodle](https://gouda.msudenver.edu/moodle/mod/assign/view.php?id=5495) is due by Sunday, September 3, 2017, 11:55 PM.

This presentation should contain the following items:
Screenshots of github
Screenshots of slack
Live demo (bring up github and slack on a laptop)
"Lightweight" retrospective (what went well, what went poorly)

Only 1 Team member will turn this in on Moodle

**Comment by cblanto7** [comment]
I turned this in
