### ISSUE TITLE
Add Junit for Test Coverage

### ISSUE THREAD

**Issue by zeonin** [MSUTeam1/unbanner#20]
As Dr. Beaty, I want to see at a glance the coverage results of our tests.

AC:
* Every person should write a Junit test (at least on their own repository)
* Junit runs aganst MSUTeam1/unbanner

**Comment by toasterbrain** [comment]
There are a bunch of versions for Junit to choose from and none of them are labeled "stable". I am going with the most recent version not marked beta. This is junit version 4.12 and it was last updated 04-Dec-2014.
