### ISSUE TITLE
Definition of "done" (criteria for commits to master)

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#24]
As the customer I want to know what the team's definition of done is. This will be the criteria they use to vet what gets committed to the master branch.
Listed on the handout for sprint 2:
* See code coverage of 95% (we need to define this b/c I don't know what it means and I doubt I am alone)
* Code reviews with at least two people (can't be the same person twice until everyone has done it)
* No findbugs or checkstyle issues
* end-user documentation
* EDIT: developer documentation (document your code!)

**Comment by toasterbrain** [comment]
Post if you think there is anything else we need to do. These requirements seem good to me.

**Comment by toasterbrain** [comment]
wait why are there 2 of these? how do we point to other cards inside of the comments?

**Comment by cblanto7** [comment]
yea there was a second made somehow on accident. #26 so ignore that one.

**Comment by Brodski** [comment]
My definition of done: A functional piece of software that does what the customer wants it to do. 

As a side, I could imagine that there might be some silly bug that shows up if you're intentionally trying to break the program, but if it works for any actual and practical use I could excuse a few bugs

**Comment by mkbhattarai** [comment]
I think we can use this when we use intellij for the code coverage
[how to view code coverage in IntelliJ](https://www.jetbrains.com/help/idea/viewing-code-coverage-results.html)
