### ISSUE TITLE
Choose a Templating Engine

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#25]
As a developer I want a templating engine as it is a valuable tool for building views as a part of the MVC design paradigm that we will be using for this application

Some options are Mustache, Groovy, and Time (SP?)
Im sure there are others as well.
Comment with your vote.

**Comment by Brodski** [comment]
I'd choose groovy b/c it seems to be popular. I could google "Groovy Tutorial" and get some useful results, unlike mustache or time tutorial. Also, groovy's wikipedia is sizable (much more mustache's), the wiki says IntelliJ and Eclipse (among others) support groovy, it's possible that the other templating engines do too but knowing that groovy is supported helps convince it to me, and (once again) android studio uses groovy, so it will be valuable for that.

**Comment by cblanto7** [comment]
http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html easy to use with spring

**Comment by Brodski** [comment]
Another reason I want groovy is b/c it seems to go hand in hand with gradle, for example the entire gradle API is designed in the groovy language.

**Comment by cblanto7** [comment]
going with thymeleaf for now
