### ISSUE TITLE
Create an index.html

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#28]
As the customer I want to be able to navigate and possibly look at the web application I am paying for.
* links to the 4 parts of CRUD (create, read, update, delete) as they relate to the persistent Student class #27 
* link to documentation

**Comment by cblanto7** [comment]
This will be generated automatically from Spring Boot. I am assigning this task to myself for now.

**Comment by cblanto7** [comment]
#31

**Comment by cblanto7** [comment]
#38 changes made to index it is now a template and not a static page.
