### ISSUE TITLE
Write a controller

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#30]
As a developer I want the StudentController.java file to be written for our app. (right now it is blank)

Dr. Beaty has suggested 4 different people each write a piece of CRUD (create, read, update, delete), presumably for the persistent Student class.

**Comment by cblanto7** [comment]
#38 Implemented Some of the StudentController.java in this pull request, still needs POST methods so we can implement the CRUD operations

**Comment by cblanto7** [comment]
#39 delete is now done with this pull request

**Comment by toasterbrain** [comment]
the controller is written. the CRUD operations have been turned into their own issues. closed.

**Comment by zeonin** [comment]
Deleting this story in lieu of individual issues.
