### ISSUE TITLE
Choose a style and get a style checker for consistent code.

### ISSUE THREAD

**Issue by zeonin** [MSUTeam1/unbanner#4]
As a developer, I want the code that I'm working with to have a consistent look and feel. This is usually referred to as a [Style Guide](https://en.wikipedia.org/wiki/Style_guide). I propose that our team look into and adopt or develop a style guide so our code also has a consistent look.

A couple of examples:
* [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)
* [Oracle Java Style Guide](http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html)

Furthermore, once a style guide is selected/developed, it should be documented in the project's wiki for easy reference.

As a developer, I want to use a program or perhaps an Intellij plugin to check my code for style issues before I submit said code. I would like a list of possible programs/plugins to choose from that will perform this task. After choosing one I will install it and make sure it runs (properly).

Tracker for everyone installing the CheckStyle plugin:

- [x] @Brodski 
- [x] @cblanto7 
- [ ] @mkbhattarai 
- [x] @nbarnes7 
- [x] @toasterbrain 
- [x] @zeonin

**Comment by blakeappine** [comment]
I don't mind which style we use, however Google Java Style Guide may be easier to read.

**Comment by toasterbrain** [comment]
I prefer the google example code at a glance.

**Comment by Brodski** [comment]
I don't care.

**Comment by toasterbrain** [comment]
everyone tag removed. I was mistakenly under the impression we all had to add something to our personal computers

**Comment by cblanto7** [comment]
I think it actually should actually be an everyone tag, everyone should install the CheckStyle IDEA plugin in their IDE

**Comment by cblanto7** [comment]
https://plugins.jetbrains.com/plugin/1065-checkstyle-idea

this one

**Comment by toasterbrain** [comment]
thanks for the good links casey

**Comment by nbarnes7** [comment]
I installed the CheckStyle plugin

**Comment by mkbhattarai** [comment]
I also installed checkstyle for Intellij

**Comment by toasterbrain** [comment]
I did this sometime last week and mahesh said somewhere that he installed it. the checklist only works if people look at it. I mainly check in on slack #54
