### ISSUE TITLE
Create global variables

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#41]
As a developer I want to be able to change these values across the application by changing only one variable.
* School name
* Credit hours per level
This is my best guess as to what the customer wants for this story point. Double check it. Does this class need to support CRUD operations?

**Comment by toasterbrain** [comment]
Should we put these all in the same class so they are all together or attach them to the classes they belong to? I vote for one class containing all globals.

**Comment by cblanto7** [comment]
I believe this is how we should implement globals in spring 4.x
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/context/request/RequestContextHolder.html

**Comment by nbarnes7** [comment]
signing up for this, wish me luck

**Comment by nbarnes7** [comment]
This is done and looks tested
