### ISSUE TITLE
Course persistence class

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#42]
As the customer I want to be able to create class listings in the database. These listings need to keep track of:
* What department they are from
* Number (clarify with customer)
* How many credits they are worth
* A description of the course
* Prerequisite courses and level (freshman, soph, jr, sr, grad)
* Corerequisite courses (clarify with customer)
This class should have CRUD operations.

**Comment by toasterbrain** [comment]
needs: class, controller, http templates

**Comment by nbarnes7** [comment]
I'm closing this, it is tested and is done. (can reopen it if I'm wrong)
