### ISSUE TITLE
Sections persistence class

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#43]
I have no idea what the customer wants in this instance. PO should ask him.

**Comment by nbarnes7** [comment]
This is the class Dr. Beaty said would be the most tricky this sprint. It was described to me by Dr. Beaty as involving a pivot table or join table, Casey said this involved mySQL, so our implementation of this may be different using Mongo. As I understand it sections should have references to courses/professors, courses/professors should have drop down menus of sections.

**Comment by nbarnes7** [comment]
We need to add two more attributes for the section class, semester and professor. Changes will need to be made in sections.java, section controller, and section.html.

**Comment by cblanto7** [comment]
this is more or less completed so I am closing this card
