### ISSUE TITLE
Read operation for student class / Including tests

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#46]
As the customer I want to be able to view information about a single student. I may also want to view a complete list of all students.
As a developer I want to know how to write a test case for this type of method such that I can use TDD for all future read methods.

**Comment by cblanto7** [comment]
edited title of card to reflect that we need tests for this CRUD operation

**Comment by toasterbrain** [comment]
I have written some tests that fail and realized the main problem I am running into is that I cant reference the repository statically because it isn't static. help
