### ISSUE TITLE
Learn about TDD

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#47]
As a developer I want to learn about TDD so I can satisfy the definition of done among other things.
* I want to know how to write tests for the CRUD operations being done on the student class.
* I vow to write tests before code for the second half of this sprint. (globals, courses, sections)
This is the focus of this sprint as without it nothing we do matters.

**Comment by toasterbrain** [comment]
Haven't done a ton of research but it seems we need mocks to test the database functions because the database isn't static. It is possibly redundant but I would like to know of some way to query the database and know what all is in there.

**Comment by mkbhattarai** [comment]
This is done already in sprint 3
