### ISSUE TITLE
Everyone needs to get a bugFinder

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#49]
As a developer I want to make sure my code isn't buggy before pushing it and having it reviewed as this wastes everyone else's time. To this end I want a program/plugin that will check my code for bugs.

this is an Intellij plugin casey found: https://plugins.jetbrains.com/plugin/3847-findbugs-idea
install: CTRL+ALT+s  >> plugins >> install plugin from disk >> select the zip file you downloaded >> restart intellij
use: right click in intellij >> fingbugs >> analyse current file

**Comment by cblanto7** [comment]
this is the one we should use

https://plugins.jetbrains.com/plugin/3847-findbugs-idea

**Comment by nbarnes7** [comment]
I downloaded the one Casey suggested.

**Comment by mkbhattarai** [comment]
i installed find bugs

**Comment by toasterbrain** [comment]
pretty sure everyone has done this. correct me if I am wrong by re-opening the issue, installing findbugs, and re-closing the issue.
