### ISSUE TITLE
Learn about testing tools

### ISSUE THREAD

**Issue by toasterbrain** [MSUTeam1/unbanner#50]
As a developer I want to use TDD. To do this I need to know how to write tests and use the test tools I already have. These are:
* The part of mongo that lets you add fake db entries
* mockito
* junit
* AssertJ
* Hamcrest

**Comment by mkbhattarai** [comment]
I will start learning mockito and junit first then I will learn others

**Comment by cblanto7** [comment]
I feel that everyone had a chance to do this last sprint, so I am closing this issue
